services:
  backend:
    build: ./backend
    container_name: foxx-system-api
    restart: always
    ports:
      - "3020:3020"
    volumes:
      # PersistÃªncia do banco de dados SQLite
      - sqlite_data:/app

  frontend:
    build: ./frontend
    container_name: foxx-system-web
    restart: always
    ports:
      - "3000:80" # Acessar no navegador via localhost:3000
    depends_on:
      - backend

volumes:
  sqlite_data:
